
services:
  
  server:
    build:
      context: .
    command: gunicorn numble.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - type: bind
        source: ./static
        target: /app/static/
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      - type: bind
        source: ./static
        target: /app/static/
    ports:
      - 1337:80
    depends_on:
      - server
