
services:
  
  server:
    build:
      context: .
    command: gunicorn numble.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static/
      - static_volume_admin:/app/static/admin/
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static/
      - static_volume_admin:/app/static/admin/
    ports:
      - 1337:80
    depends_on:
      - server

volumes:
  static_volume:
  static_volume_admin: