# Generated by Django 5.0.4 on 2024-05-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0002_game_delete_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="author",
            new_name="user",
        ),
    ]
