# Generated by Django 5.0.4 on 2024-05-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0004_game_game_mode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Game",
        ),
    ]
