# Generated by Django 5.0.4 on 2024-05-02 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("play", "0005_delete_game"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("finish_time", models.TimeField()),
                ("duration", models.DurationField()),
                ("number_of_tries", models.IntegerField()),
                (
                    "game_mode",
                    models.CharField(
                        choices=[
                            ("easy", "Easy Game Mode"),
                            ("medium", "Medium Game Mode"),
                            ("hard", "Hard Game Mode"),
                            ("daily", "Daily Numble"),
                        ],
                        default="easy",
                        max_length=6,
                    ),
                ),
                ("game_completed", models.BooleanField(default=False)),
                ("number", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
