# Generated by Django 5.0.4 on 2024-05-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0007_game_tries_alter_game_game_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="duration",
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="finish_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="number_of_tries",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="game",
            name="tries",
            field=models.JSONField(default={}),
        ),
    ]
