# Generated by Django 5.0.4 on 2024-05-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0009_alter_game_tries"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_won",
            field=models.BooleanField(default=False),
        ),
    ]
