# Generated by Django 5.0.4 on 2024-05-07 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0010_game_game_won"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="expire_time",
            field=models.TimeField(
                default=datetime.datetime(
                    2024, 5, 7, 19, 30, 9, 51839, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
