# Generated by Django 5.0.4 on 2024-05-07 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0011_game_expire_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="expire_date",
            field=models.DateField(default=datetime.date(2024, 5, 7)),
            preserve_default=False,
        ),
    ]
