# Generated by Django 5.0.4 on 2024-06-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0015_streak"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_mode",
            field=models.CharField(
                choices=[
                    ("easy", "Easy Game Mode"),
                    ("medium", "Medium Game Mode"),
                    ("hard", "Hard Game Mode"),
                    ("daily", "Daily Numble"),
                    ("blind", "Blind Game Mode"),
                    ("2d", "2 Dimensional Game Mode"),
                ],
                max_length=6,
            ),
        ),
    ]
