# Generated by Django 5.0.4 on 2024-06-17 11:34

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0018_resetpassword"),
    ]

    operations = [
        migrations.AddField(
            model_name="resetpassword",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 17, 11, 34, 29, 22606, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resetpassword",
            name="token",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resetpassword",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
