# Generated by Django 5.0.4 on 2024-06-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0019_resetpassword_expire_date_resetpassword_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpassword",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="resetpassword",
            name="expire_date",
            field=models.DateTimeField(),
        ),
    ]
