# Generated by Django 5.0.4 on 2024-06-23 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0020_alter_resetpassword_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game2d",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("finish_time", models.DateTimeField(null=True)),
                ("duration", models.DurationField(null=True)),
                ("expire_time", models.DateTimeField()),
                ("number_of_tries", models.IntegerField(default=0)),
                ("game_mode", models.CharField(default="2d", max_length=6)),
                ("game_completed", models.BooleanField(default=False)),
                ("number", models.CharField(max_length=10)),
                ("number2", models.CharField(max_length=10)),
                ("tries", models.JSONField(default=dict)),
                ("game_won", models.BooleanField(default=False)),
                ("lose_reason", models.CharField(max_length=256, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
