# Generated by Django 5.0.4 on 2024-06-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0021_game2d"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="number2",
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Game2d",
        ),
    ]
