# Generated by Django 5.0.4 on 2024-06-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0022_game_number2_delete_game2d"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="tries2",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="number2",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
