# Generated by Django 5.0.4 on 2024-07-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0024_game_pivot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="lose_reason",
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
