# Generated by Django 5.0.4 on 2024-07-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0025_alter_game_lose_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="lose_reason",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
